//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTGproject.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise_bodypart
    {
        public int fk_exercise_exerciseID { get; set; }
        public int fk_bodypart_bodypartID { get; set; }
        public decimal EMG { get; set; }
    
        public virtual Bodypart Bodypart { get; set; }
        public virtual Exercis Exercis { get; set; }
    }
}
