//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTGproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercise()
        {
            this.Exercise_bodypart = new HashSet<Exercise_bodypart>();
        }
    
        public int exerciseID { get; set; }
        public string exerciseName { get; set; }
        public Nullable<decimal> C1RM { get; set; }
        public Nullable<int> fk_training_trainingID { get; set; }
        public string fk_exercise_categoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exercise_bodypart> Exercise_bodypart { get; set; }
        public virtual Training Training { get; set; }
        public virtual Exercise_category Exercise_category { get; set; }
    }
}
